"""Adding contacts view

Revision ID: cbfe9d3cc100
Revises: 885a1a2d71f8
Create Date: 2025-03-07 21:46:56.995148

"""
import sqlmodel
from typing import Sequence, Union
from app.models import _Contact

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfe9d3cc100'
down_revision: Union[str, None] = '885a1a2d71f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE VIEW contacts AS
        SELECT
            id,
            phone_number,
            office_id,
            'patient' AS type
        FROM
            patient
        UNION ALL
        SELECT
            id,
            phone_number,
            office_id,
            'doctor' AS type
        FROM
            doctor
        UNION ALL
        SELECT
            id,
            phone_number,
            office_id,
            'manager' AS type
        FROM
            manager
        UNION ALL
        SELECT
            id,
            phone_number,
            office_id,
            'owner' AS type
        FROM
            owner
        """
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP VIEW contacts
        """
    )
    pass
    # ### end Alembic commands ###
